---
- name: update apt
  apt: >
    update_cache=yes
    cache_valid_time=3600

- name: install deps
  apt: >
    pkg={{item}}
    state=installed
  with_items:
    - unzip

- name: create consul-template directory structure
  file: >
    state=directory
    path={{ item }}
  with_items:
    - "{{ consul_template_home }}"
    - "{{ consul_template_home }}/bin"
    - "{{ consul_template_home }}/config"

- name: copy consul-template binary
  copy : >
    src={{ consul_template_binary }}
    dest={{ consul_template_home }}/bin
    mode=0755

- name: copy consul-template systemd service configuration
  template: >
    src=consul-template.service.j2
    dest=/etc/systemd/system/consul-template.service
    mode=0755

- name: add consul-template to path through profile.d
  template: >
    src=consul-template.sh.j2
    dest=/etc/profile.d/consul-template.sh
    owner=root
    group=root
    mode=0755

- name: consul-template config file
  template: >
    src=consul-template.cfg.j2
    dest={{ consul_template_home }}/config/{{ consul_template_config_file }}
    mode=0755
